# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-13 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1', models.CharField(default='', max_length=255)),
                ('c2', models.CharField(default='', max_length=255)),
                ('c3', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'db_cases',
            },
        ),
    ]
